// 导入页面路由模块
import { router } from '@kit.ArkUI';
import { BusinessError } from '@kit.BasicServicesKit';

@Entry
@Component
struct Second {
  @State message: string = 'Hi there'

  // fetchData = () => {
  //
  //   let request = new http.HttpRequest();
  //   request.method = 'GET';
  //   request.url = 'https://api.example.com/data'; // 替换为你的API URL
  //   request.subscribe(
  //     (response) => {
  //       if (response.statusCode == 200) {
  //         this.message = 'Response received: ' + response.data;
  //       } else {
  //         this.message = 'Error: ' + response.statusCode;
  //       }
  //     },
  //     (error) => {
  //       this.message = 'Error: ' + error;
  //     }
  //   );
  //   request.send();
  // }
  build() {
    Row() {
      Column() {
        Text(this.message)
          .fontSize(50)
          .fontWeight(FontWeight.Bold)
        Button() {
          Text('Back')
            .fontSize(25)
            .fontWeight(FontWeight.Bold)
        }
        .type(ButtonType.Capsule)
        .margin({
          top: 20
        })
        .backgroundColor('#0D9FFB')
        .width('40%')
        .height('5%')
        // 返回按钮绑定onClick事件，点击按钮时返回到第一页
        .onClick(() => {
          console.info(`Succeeded in clicking the 'Back' button.`)
          try {
            // 返回第一页
            router.back()
            console.info('Succeeded in returning to the first page.')
          } catch (err) {
            let code = (err as BusinessError).code;
            let message = (err as BusinessError).message;
            console.error(`Failed to return to the first page. Code is ${code}, message is ${message}`)
          }
        })
      }
      .width('100%')
    }
    .height('100%')
  }
}